// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPz7DH7hhC1Jgab73t8ymfF7OfxIW-HtU',
    appId: '1:419126786648:web:17cbedb622666fa335e82d',
    messagingSenderId: '419126786648',
    projectId: 'textimagepdfpicker',
    authDomain: 'textimagepdfpicker.firebaseapp.com',
    storageBucket: 'textimagepdfpicker.appspot.com',
    measurementId: 'G-612FP5LKQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnAcDtNqzb9BL7xqlA_G2wJYM2yUEHlB0',
    appId: '1:419126786648:android:92367ad05917307435e82d',
    messagingSenderId: '419126786648',
    projectId: 'textimagepdfpicker',
    storageBucket: 'textimagepdfpicker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUnHL3BY_IORPne_ufEDsT640OsE_lFy8',
    appId: '1:419126786648:ios:2c16186bbfe8a01e35e82d',
    messagingSenderId: '419126786648',
    projectId: 'textimagepdfpicker',
    storageBucket: 'textimagepdfpicker.appspot.com',
    iosBundleId: 'com.example.textImagePdfPicker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUnHL3BY_IORPne_ufEDsT640OsE_lFy8',
    appId: '1:419126786648:ios:2c16186bbfe8a01e35e82d',
    messagingSenderId: '419126786648',
    projectId: 'textimagepdfpicker',
    storageBucket: 'textimagepdfpicker.appspot.com',
    iosBundleId: 'com.example.textImagePdfPicker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPz7DH7hhC1Jgab73t8ymfF7OfxIW-HtU',
    appId: '1:419126786648:web:409953937d022f5835e82d',
    messagingSenderId: '419126786648',
    projectId: 'textimagepdfpicker',
    authDomain: 'textimagepdfpicker.firebaseapp.com',
    storageBucket: 'textimagepdfpicker.appspot.com',
    measurementId: 'G-WE5RXZ0REY',
  );
}
